import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Protection from '../utils/ProtecRouter';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Protection>
      <body className={inter.className}>
          <main className='w-screen h-screen flex flex-col items-center justify-center'>
            <nav className='w-screen h-14 absolute top-0 flex justify-evenly items-center'>
              <Link className='w-fir h-fit p-2 border-[1px] border-zinc-700 rounded-lg bg-white cursor-pointer' href={"/user"}>User</Link>
              <Link className='w-fir h-fit p-2 border-[1px] border-zinc-700 rounded-lg bg-white cursor-pointer' href={"/contacts"}>Contacts</Link>
            </nav>
            {children}
          </main>  
        </body>
      </Protection>
    </html>
  )
}
